name: morpheus
channels:
  - defaults
  - conda-forge
dependencies:
  # Runtime
  - attrdict3=2.0.2
  - wxPython=4.2.1
  - python=3.11
  - pydantic=2.0.3
  - pandas=2.0.3
  - rich=13.4.2
  - skillbridge=1.5.0
 # Development and Testing
  - PyInstaller=5.13.0
  - conda=23.5.2
  - mamba=1.4.9
  - pip=23.2
  - flit=3.9.0
  - pytest=7.4.0
  - pylint=2.17.4
  - pre-commit=2.*
  # documentation
  - mkdocs=1.4.3
  - mkdocs-material=9.1.19
