[project]
name = "morpheus"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version", "description"]

[project.urls]
Source = "https://github.com/cascode-labs/morpheus"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"