# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri Jun 30 08:17:04 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class GUIViewer(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GUI_Viewer.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Morpheus Test Bench Generator")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        wxglade_tmp_menu.Append(wx.ID_ANY, "Save", "")
        wxglade_tmp_menu.Append(wx.ID_ANY, "Save as", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        self.frame_statusbar = self.CreateStatusBar(1)
        self.frame_statusbar.SetStatusWidths([-1])
        # statusbar fields
        frame_statusbar_fields = ["frame_statusbar"]
        for i in range(len(frame_statusbar_fields)):
            self.frame_statusbar.SetStatusText(frame_statusbar_fields[i], i)

        self.panel_main = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_SIMPLE)
        
        rows = 3
        #1) CONFIG FILE
        #2) Testbench File
        #3) RUN BUTTON
        self.header = wx.FlexGridSizer(4, 1, 0, 0)
        grid_sizer_1 = wx.FlexGridSizer(4, 1, 0, 0)

        grid_sizer_2 = wx.FlexGridSizer(3, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)



#GET CONFIG FILES SELECTION
        configs_txt = wx.StaticText(self.panel_main, wx.ID_ANY, "Select Config File")
        grid_sizer_2.Add(configs_txt, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 50)
        #self.configs_sel = wx.ComboBox(self.panel_main, wx.ID_ANY, style=wx.CB_DROPDOWN | wx.CB_READONLY)
        #configs_sel.Bind(wx.EVT_COMBOBOX_CLOSEUP,self.populateCells)

        sellib_txt = wx.StaticText(self.panel_main, wx.ID_ANY, "Select Testbench Library")
        grid_sizer_2.Add(sellib_txt, 0, wx.ALIGN_CENTER | wx.LEFT | wx.RIGHT, 50)

        self.sel_lib = wx.ComboBox(self.panel_main, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        grid_sizer_2.Add(self.sel_lib, 0, wx.ALL | wx.EXPAND, 2)

        dutlib_txt = wx.StaticText(self.panel_main, wx.ID_ANY, "Select DUT Library")
        grid_sizer_2.Add(dutlib_txt, 0, wx.ALIGN_CENTER, 0)

        self.sel_dut_lib = wx.ComboBox(self.panel_main, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        grid_sizer_2.Add(self.sel_dut_lib, 0, wx.ALL | wx.EXPAND, 2)

        dutcell_txt = wx.StaticText(self.panel_main, wx.ID_ANY, "Select DUT Cell")
        grid_sizer_2.Add(dutcell_txt, 0, wx.ALIGN_CENTER, 0)

        self.sel_dut_cell = wx.ComboBox(self.panel_main, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY)
        grid_sizer_2.Add(self.sel_dut_cell, 0, wx.ALL | wx.EXPAND, 2)

        self.btn_reeval = wx.Button(self.panel_main, wx.ID_ANY, "Re-evaluate")
        self.btn_reeval.SetMinSize((170, 30))
        self.btn_reeval.SetMaxSize((170, 30))
        grid_sizer_1.Add(self.btn_reeval, 0, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE | wx.LEFT, 10)
        self.btn_reeval.Hide()

        grid_sizer_3 = wx.FlexGridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND | wx.LEFT | wx.RIGHT, 10)

        self.btn_mktest = wx.Button(self.panel_main, wx.ID_ANY, "Make Test\n")
        self.btn_mktest.SetMinSize((170, 30))
        grid_sizer_3.Add(self.btn_mktest, 0, 0, 10)

        self.sel_test = wx.ComboBox(self.panel_main, wx.ID_ANY, style=wx.CB_DROPDOWN | wx.CB_READONLY)
        self.sel_test.SetSelection(0)
        grid_sizer_3.Add(self.sel_test, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL | wx.EXPAND, 2)

        self.testbench_tabs = wx.Notebook(self.panel_main, wx.ID_ANY)
        self.testbench_tabs.Hide()
        grid_sizer_1.Add(self.testbench_tabs, 1, wx.EXPAND, 0)

        grid_sizer_3.AddGrowableRow(0)
        grid_sizer_3.AddGrowableCol(1)

        grid_sizer_2.AddGrowableRow(0)
        grid_sizer_2.AddGrowableRow(1)
        grid_sizer_2.AddGrowableRow(2)
        grid_sizer_2.AddGrowableCol(1)

        grid_sizer_1.AddGrowableRow(3)
        grid_sizer_1.AddGrowableCol(0)
        self.panel_main.SetSizer(grid_sizer_1)

        grid_sizer_1.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class GUI_Viewer
