# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0pre on Fri Jun 30 08:17:04 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class TabTemplate(wx.ScrolledWindow):
    def __init__(self, *args, **kwds):
        # begin wxGlade: TabTemplate.__init__
        kwds["style"] = kwds.get("style", 0) | wx.TAB_TRAVERSAL
        wx.ScrolledWindow.__init__(self, *args, **kwds)
        self.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_MENU))
        self.SetScrollRate(10, 10)

        self.sizer_2 = wx.BoxSizer(wx.VERTICAL)
        
        # end wxGlade

# end of class TabTemplate
